services:
  studio-scheduler:
    build: .
    ports:
      - "3000:80"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/health"]
      interval: 5s
      timeout: 3s
      retries: 10
